name: Typos
on:
  pull_request:
    branches-ignore:
      - gh-pages
      - releases/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0

      - name: Spell check
        uses: crate-ci/typos@0c17dabcee8b8f1957fa917d17393a23e02e1583 # v1.36.3
